config/routes.rb
Rails.application.routes.draw do

  # 静的なページ
  root 'static_pages#home'
  get  '/about_app',    to: 'static_pages#about_app'
  get  '/about_me',   to: 'static_pages#about_me'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'employees#new'
  
  # ログイン関係
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest_login', to: 'sessions#guest'
  
  # 従業員関連
  resources :employees
  
  # 日報関連
  resources :reports, only: [:create, :destroy]
  
  # チャット関連
  get '/chat', to: 'rooms#show'
  resources :messages, only: :create
  mount ActionCable.server => '/cable'
  get '/show_additionally', to: 'rooms#show_additionally'
  
  # FAQ関係
  resources :faqs
  get '/faqs/serch', to: 'faqs#serch'

  # フォロー関連
  resources :employees do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @report  = current_employee.reports.build
      @timeline_items = current_employee.timeline.paginate(page: params[:page])
    end
  end

  def about_me
  end
  
  def about_app
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about_app.html.erb
<% provide(:title, "システムについて") %>

<h1>このシステムについて</h1>
<p>
  コールセンターなどで使用されるFAQ管理システムを意識して作成しました。実装した機能は、以下の通りです。
</p>

<ul>
  <li>FAQ管理・参照</li>
  <li>社内周知管理・参照</li>
  <li>従業員管理</li>
  <li>問い合わせ内容記録・参照</li>
  <li>従業員同士のフォロー機能</li>
</ul>

<p>
  システムの体験をご希望の方は、お手数ですが下記の手順に沿ってログインをお願いいたします。
</p>

<ul>
  <li>上のタブの「ホーム」ボタンをクリック</li>
  <li>画面中央のログインフォームに、下記のアドレスとパスワードを入力</li>
  <li>アドレス：example@rails-tutorial.com</li>
  <li>パスワード：Pass＠1234</li>
</ul>

app/views/static_pages/about_me.html.erb
<% provide(:title, "作成者について") %>

<h1>このシステムの作成者について</h1>
<p>
  片野直人と申します。私のポートフォリオをご覧になっていただき、ありがとうございます。
</p>
<p>
  職務経歴書と、過去に作成したポートフォリオのGitHubリンクです。ご確認頂けたら幸いです。  
</p>

<br><br>

<p>
  職務経歴書（google driveに公開したpdfファイルが開かれます）
</p>
<p>
  <a href="https://drive.google.com/file/d/1JbpT1B6Gqd2d-w_kLc02C6uS-1Yaxr6C/view?usp=sharing">
    https://drive.google.com/file/d/1JbpT1B6Gqd2d-w_kLc02C6uS-1Yaxr6C/view?usp=sharing
  </a>
</p><br>

<p>
  日報管理システム（Servlet/jspで作成）
</p>
<p>
  <a href="https://github.com/neioge/daily_report_sample.git">
    https://github.com/neioge/daily_report_sample.git
  </a>
</p><br>

<p>
  Todo管理アプリ（Docker/LEMP/Laravelで作成）
</p>
<p>
  <a href="https://github.com/neioge/docker-laravel-todo.git">
    https://github.com/neioge/docker-laravel-todo.git
  </a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'コンタクト') %>
<h1>コンタクト</h1>
<p>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="employee_info">
        <%= render 'shared/employee_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="report_form">
        <%= render 'shared/report_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>日報一覧</h3>
      <%= render 'shared/timeline' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>FAQ管理システムへようこそ</h1>
    
    <%= link_to "ログイン", login_path,  class: "btn btn-lg btn-primary" %>
    <%= link_to 'ゲストログイン', guest_login_path, method: :post, class: "btn btn-lg btn-info"%>
  </div>
<% end %>