config/routes.rb
Rails.application.routes.draw do

  # 静的なページ
  root 'static_pages#home'
  get  '/about_app',    to: 'static_pages#about_app'
  get  '/about_me',   to: 'static_pages#about_me'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'employees#new'
  
  # ログイン関係
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest_login', to: 'sessions#guest'
  
  # 従業員関連
  resources :employees
  
  # 日報関連
  resources :reports, only: [:create, :destroy]
  
  # チャット関連
  get '/chat', to: 'rooms#show'
  resources :messages, only: :create
  mount ActionCable.server => '/cable'
  get '/show_additionally', to: 'rooms#show_additionally'
  
  # FAQ関係
  resources :faqs
  get '/faqs/serch', to: 'faqs#serch'

  # フォロー関連
  resources :employees do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  
end

app/views/shared/_answer.html.erb
<p>ここに、FAQの回答を表示する。DOM操作を使って、クリックされた質問に紐づいている回答を都度表示する。</p>

app/views/shared/_employee_info.html.erb
<%= link_to gravatar_for(current_employee, size: 50), current_employee %>
<h1><%= current_employee.name %></h1>
<span><%= link_to "マイページ", current_employee %></span>
<span>作成した日報　<%= current_employee.reports.count %></span>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力内容に誤りがあります <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_question_info.html.erb
<p id='activeQuestion'>右側の質問をクリックしてください</p>  

app/views/shared/_report_form.html.erb
<%= form_with(model: @report, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "お疲れ様です..." %>
  </div>
  <%= f.submit "日報作成", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @employee ||= current_employee %>
<div class="stats">
  <a href="<%= following_employee_path(@employee) %>">
    <strong id="following" class="stat">
      <%= @employee.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_employee_path(@employee) %>">
    <strong id="followers" class="stat">
      <%= @employee.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_timeline.html.erb
<% if @timeline_items.any? %>
  <ol class="reports">
    <%= render @timeline_items %>
  </ol>
  <%= will_paginate @timeline_items,
                    params: { controller: :static_pages, action: :home } %>
<% end %>