config/routes.rb
Rails.application.routes.draw do

  # 静的なページ
  root 'static_pages#home'
  get  '/about_app',    to: 'static_pages#about_app'
  get  '/about_me',   to: 'static_pages#about_me'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'employees#new'
  
  # ログイン関係
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/guest_login', to: 'sessions#guest'
  
  # 従業員関連
  resources :employees
  
  # 日報関連
  resources :reports, only: [:create, :destroy]
  
  # チャット関連
  get '/chat', to: 'rooms#show'
  resources :messages, only: :create
  mount ActionCable.server => '/cable'
  get '/show_additionally', to: 'rooms#show_additionally'
  
  # FAQ関係
  resources :faqs
  get '/faqs/serch', to: 'faqs#serch'

  # フォロー関連
  resources :employees do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "作成者について",   about_me_path %></li>
      <li><%= link_to "コンタクト", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-dark bg-primary">
  <div class="container">
    <%= link_to "FAQ管理システム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to '日報管理', root_path %></li>
          <li><%= link_to 'FAQ管理', faqs_path %></li>
          <li><%= link_to "従業員管理", employees_path %></li>
          <li><%= link_to "チャット", chat_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">アカウント<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_employee %></li>
              <li><%= link_to "設定", edit_employee_path(current_employee) %></li>
              <li><%= link_to "システムについて", about_app_path %></li>
              <li class="divider"></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'ホーム', root_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>